// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteUserByIDRequest struct {
	ID string `json:"id"`
}

type GetTransactoinByID struct {
	ID string `json:"id"`
}

type GetUserByID struct {
	ID string `json:"id"`
}

type NewTransaction struct {
	Name   string `json:"name"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Transaction struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type TransactionByID struct {
	ID string `json:"id"`
}

type UpdateUserByIDRequest struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type User struct {
	ID           string         `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	Transactions []*Transaction `json:"transactions"`
}
