// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/golang-graphql/graph"
	"github.com/golang-graphql/graph/repository"
	"github.com/golang-graphql/graph/service"
	"github.com/golang-graphql/infrastructure"
)

// Injectors from injector.go:

func InitializedServer() *handler.Server {
	config := infrastructure.NewConfig()
	database := infrastructure.NewMongoDatabase(config)
	userRepository := repository.NewUserRepository(database)
	userService := service.NewUserService(userRepository)
	transactionRepository := repository.NewTransactionRepository(database)
	transactionService := service.NewTransactionService(transactionRepository)
	server := graph.NewHandler(userService, transactionService)
	return server
}
